# .pre-commit-config.yaml
default_stages: [commit]
minimum_pre_commit_version: 3.0.0
default_language_version:
  python: python3.11.9
# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-merge-conflict
      # - id: no-commit-to-branch
      #   args: ["--branch", "main"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: [flake8-bugbear, flake8-comprehensions]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies: [numpy]

  # - repo: https://github.com/pre-commit/mirrors-pylint
  #   rev: v2.14.5
  #   hooks:
  #     - id: pylint

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
      - id: python-check-blanket-noqa
